### ISSUE TITLE
Can't install in project

### ISSUE THREAD

**Issue by beningreenjam** [iotacss/iotaplate#6]
I've just globally updated to the latest iotaplate version, created a new project with a `package.json` file and ran `npm install`, which has successfully installed all my dependencies.

I then navigate from my project root to the `/src/sass` directory and attempted to run the `iotaplate` command. I expect it create the sass files in the current working directory, however it outputs the following error:

```
assert.js:265
    throw err;
    ^

AssertionError [ERR_ASSERTION]: A name parameter is required to create a storage
    at new module.exports (/usr/local/lib/node_modules/iotaplate/node_modules/yeoman-generator/lib/util/storage.js:24:3)
    at module.exports.Base._getStorage (/usr/local/lib/node_modules/iotaplate/node_modules/yeoman-generator/lib/index.js:567:10)
    at new module.exports (/usr/local/lib/node_modules/iotaplate/node_modules/yeoman-generator/lib/index.js:138:22)
    at new module.exports (/usr/local/lib/node_modules/iotaplate/app/index.js:5:18)
    at Environment.instantiate (/usr/local/lib/node_modules/iotaplate/node_modules/yeoman-environment/lib/environment.js:336:10)
    at Environment.create (/usr/local/lib/node_modules/iotaplate/node_modules/yeoman-environment/lib/environment.js:313:15)
    at Environment.run (/usr/local/lib/node_modules/iotaplate/node_modules/yeoman-environment/lib/environment.js:372:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/iotaplate/cli.js:10:5)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
```

I'm running Node v10.2.1 and NPM v6.1.0.

**Comment by beningreenjam** [comment]
It worked after I realised the error relates to my project's `package.json` file not having a `name` property and so added one.
